# Generated by Django 3.2.25 on 2024-07-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='up_usersdetails',
            old_name='first_name',
            new_name='UserName',
        ),
        migrations.RemoveField(
            model_name='up_usersdetails',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='up_usersdetails',
            name='middle_name',
        ),
    ]
