# Generated by Django 3.2.25 on 2024-07-20 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240720_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='up_usersdetails',
            name='store_image',
        ),
    ]
