# Generated by Django 3.2.25 on 2024-07-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_up_usersdetails_store_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='up_usersdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
